--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.veripass_consent_receipt_status
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("veripass_consent_receipt_status", function()
  local openapiclient_veripass_consent_receipt_status = require "openapiclient.model.veripass_consent_receipt_status"

end)
