--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.veripass_ping_response
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("veripass_ping_response", function()
  local openapiclient_veripass_ping_response = require "openapiclient.model.veripass_ping_response"

  -- unit tests for the property 'timestamp'
  describe("property timestamp test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'version'
  describe("property version test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
