--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.veripass_g1_hash_set
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("veripass_g1_hash_set", function()
  local openapiclient_veripass_g1_hash_set = require "openapiclient.model.veripass_g1_hash_set"

  -- unit tests for the property 'hashes'
  describe("property hashes test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
