--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.vpc_auth_info
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("vpc_auth_info", function()
  local openapiclient_vpc_auth_info = require "openapiclient.model.vpc_auth_info"

  -- unit tests for the property 'customer_id'
  describe("property customer_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
