--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.vpc_self_age_eligibility_response
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("vpc_self_age_eligibility_response", function()
  local openapiclient_vpc_self_age_eligibility_response = require "openapiclient.model.vpc_self_age_eligibility_response"

  -- unit tests for the property 'eligible'
  describe("property eligible test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
