--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- googlerpc_status class
local googlerpc_status = {}
local googlerpc_status_mt = {
	__name = "googlerpc_status";
	__index = googlerpc_status;
}

local function cast_googlerpc_status(t)
	return setmetatable(t, googlerpc_status_mt)
end

local function new_googlerpc_status(code, message, details)
	return cast_googlerpc_status({
		["code"] = code;
		["message"] = message;
		["details"] = details;
	})
end

return {
	cast = cast_googlerpc_status;
	new = new_googlerpc_status;
}
