--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- veripass_consent_receipt_status class
local veripass_consent_receipt_status = {}
local veripass_consent_receipt_status_mt = {
	__name = "veripass_consent_receipt_status";
	__index = veripass_consent_receipt_status;
}

local function cast_veripass_consent_receipt_status(t)
	return setmetatable(t, veripass_consent_receipt_status_mt)
end

local function new_veripass_consent_receipt_status()
	return cast_veripass_consent_receipt_status({
	})
end

return {
	cast = cast_veripass_consent_receipt_status;
	new = new_veripass_consent_receipt_status;
}
