--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- veripass_consent_receipt class
local veripass_consent_receipt = {}
local veripass_consent_receipt_mt = {
	__name = "veripass_consent_receipt";
	__index = veripass_consent_receipt;
}

local function cast_veripass_consent_receipt(t)
	return setmetatable(t, veripass_consent_receipt_mt)
end

local function new_veripass_consent_receipt(score, updated, age, id, subjects)
	return cast_veripass_consent_receipt({
		["score"] = score;
		["updated"] = updated;
		["age"] = age;
		["id"] = id;
		["subjects"] = subjects;
	})
end

return {
	cast = cast_veripass_consent_receipt;
	new = new_veripass_consent_receipt;
}
