--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- veripass_ping_response class
local veripass_ping_response = {}
local veripass_ping_response_mt = {
	__name = "veripass_ping_response";
	__index = veripass_ping_response;
}

local function cast_veripass_ping_response(t)
	return setmetatable(t, veripass_ping_response_mt)
end

local function new_veripass_ping_response(timestamp, version)
	return cast_veripass_ping_response({
		["timestamp"] = timestamp;
		["version"] = version;
	})
end

return {
	cast = cast_veripass_ping_response;
	new = new_veripass_ping_response;
}
