--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- veripass_g1_claim class
local veripass_g1_claim = {}
local veripass_g1_claim_mt = {
	__name = "veripass_g1_claim";
	__index = veripass_g1_claim;
}

local function cast_veripass_g1_claim(t)
	return setmetatable(t, veripass_g1_claim_mt)
end

local function new_veripass_g1_claim(anchors, age)
	return cast_veripass_g1_claim({
		["anchors"] = anchors;
		["age"] = age;
	})
end

return {
	cast = cast_veripass_g1_claim;
	new = new_veripass_g1_claim;
}
