--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- vpc_age_check_receipt class
local vpc_age_check_receipt = {}
local vpc_age_check_receipt_mt = {
	__name = "vpc_age_check_receipt";
	__index = vpc_age_check_receipt;
}

local function cast_vpc_age_check_receipt(t)
	return setmetatable(t, vpc_age_check_receipt_mt)
end

local function new_vpc_age_check_receipt(score, updated)
	return cast_vpc_age_check_receipt({
		["score"] = score;
		["updated"] = updated;
	})
end

return {
	cast = cast_vpc_age_check_receipt;
	new = new_vpc_age_check_receipt;
}
