--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- vpc_self_age_eligibility_response class
local vpc_self_age_eligibility_response = {}
local vpc_self_age_eligibility_response_mt = {
	__name = "vpc_self_age_eligibility_response";
	__index = vpc_self_age_eligibility_response;
}

local function cast_vpc_self_age_eligibility_response(t)
	return setmetatable(t, vpc_self_age_eligibility_response_mt)
end

local function new_vpc_self_age_eligibility_response(eligible)
	return cast_vpc_self_age_eligibility_response({
		["eligible"] = eligible;
	})
end

return {
	cast = cast_vpc_self_age_eligibility_response;
	new = new_vpc_self_age_eligibility_response;
}
