--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- vpc_consent_request_zero class
local vpc_consent_request_zero = {}
local vpc_consent_request_zero_mt = {
	__name = "vpc_consent_request_zero";
	__index = vpc_consent_request_zero;
}

local function cast_vpc_consent_request_zero(t)
	return setmetatable(t, vpc_consent_request_zero_mt)
end

local function new_vpc_consent_request_zero(claim, subject, ttl, notify_contact, notify_visit_url, callback_url, info_url, custom_id)
	return cast_vpc_consent_request_zero({
		["claim"] = claim;
		["subject"] = subject;
		["ttl"] = ttl;
		["notifyContact"] = notify_contact;
		["notifyVisitUrl"] = notify_visit_url;
		["callbackUrl"] = callback_url;
		["infoUrl"] = info_url;
		["customId"] = custom_id;
	})
end

return {
	cast = cast_vpc_consent_request_zero;
	new = new_vpc_consent_request_zero;
}
