--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- vpc_auth_info class
local vpc_auth_info = {}
local vpc_auth_info_mt = {
	__name = "vpc_auth_info";
	__index = vpc_auth_info;
}

local function cast_vpc_auth_info(t)
	return setmetatable(t, vpc_auth_info_mt)
end

local function new_vpc_auth_info(customer_id)
	return cast_vpc_auth_info({
		["customerId"] = customer_id;
	})
end

return {
	cast = cast_vpc_auth_info;
	new = new_vpc_auth_info;
}
