--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- vpc_auth_response class
local vpc_auth_response = {}
local vpc_auth_response_mt = {
	__name = "vpc_auth_response";
	__index = vpc_auth_response;
}

local function cast_vpc_auth_response(t)
	return setmetatable(t, vpc_auth_response_mt)
end

local function new_vpc_auth_response(token)
	return cast_vpc_auth_response({
		["token"] = token;
	})
end

return {
	cast = cast_vpc_auth_response;
	new = new_vpc_auth_response;
}
