--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- vpc_self_age_eligibility_request class
local vpc_self_age_eligibility_request = {}
local vpc_self_age_eligibility_request_mt = {
	__name = "vpc_self_age_eligibility_request";
	__index = vpc_self_age_eligibility_request;
}

local function cast_vpc_self_age_eligibility_request(t)
	return setmetatable(t, vpc_self_age_eligibility_request_mt)
end

local function new_vpc_self_age_eligibility_request(token, contact, dob, min_age, max_age)
	return cast_vpc_self_age_eligibility_request({
		["token"] = token;
		["contact"] = contact;
		["dob"] = dob;
		["minAge"] = min_age;
		["maxAge"] = max_age;
	})
end

return {
	cast = cast_vpc_self_age_eligibility_request;
	new = new_vpc_self_age_eligibility_request;
}
