--[[
  prodapi.proto

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: version not set
  
  Generated by: https://openapi-generator.tech
]]

-- vpc_consent_request class
local vpc_consent_request = {}
local vpc_consent_request_mt = {
	__name = "vpc_consent_request";
	__index = vpc_consent_request;
}

local function cast_vpc_consent_request(t)
	return setmetatable(t, vpc_consent_request_mt)
end

local function new_vpc_consent_request(contact, ttl, dob, subject, name, visit_url, callback_url, info_url, custom_id, customer_id)
	return cast_vpc_consent_request({
		["contact"] = contact;
		["ttl"] = ttl;
		["dob"] = dob;
		["subject"] = subject;
		["name"] = name;
		["visitUrl"] = visit_url;
		["callbackUrl"] = callback_url;
		["infoUrl"] = info_url;
		["customId"] = custom_id;
		["customerId"] = customer_id;
	})
end

return {
	cast = cast_vpc_consent_request;
	new = new_vpc_consent_request;
}
